### ISSUE TITLE
Adjust the `npm run bracketology` script

### ISSUE THREAD

**Issue by jschulzz** [bracketclub/bracket-data#22]
Hey there! Great tool, I really enjoyed using it this season, and hope to see it grow!

As it stands, the `bracketology` command is:

`node build/bracketology.js -y $(date '+%Y') -s ncaaw && node build/bracketology.js -y $(date '+%Y') -s ncaam` 

and the build folder is under the `.npmignore` file, so this command does not work for anyone who npm installs this package. I was hoping you could either remove that line from the `.npmignore` or move the bracketology.js file somewhere where it ships out 😃

**Comment by lukekarrys** [comment]
Thanks!

Good call. I'm not sure anymore why that directory was even being ignored. 🤷‍♂

I removed the `.npmignore` and published `v4.6.0` which should have that [file included now](https://unpkg.com/bracket-data@4.6.0/build/bracketology.js).
